name: Hedgehog Sentinel EXE Factory

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install PyQt6 PyQt6-WebEngine pyinstaller

    - name: Build with PyInstaller
      run: |
        # --onedir modunu kullanıyoruz, DLL hatalarını engeller
        pyinstaller --onedir --windowed --collect-all PyQt6 --collect-all PyQt6_WebEngine --name "Hedgehog_Sentinel" main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Hedgehog_Sentinel_Windows_Package
        path: dist/Hedgehog_Sentinel/
