name: Hedgehog Sentinel Final Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Python Setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Libraries
      run: |
        pip install PyQt6 PyQt6-WebEngine pyinstaller

    - name: Generate Folder Distribution
      run: |
        # --onedir modu DLL hatalarını kökten çözer
        pyinstaller --onedir --windowed --name "Hedgehog_Sentinel" main.py

    - name: Upload Finished Program
      uses: actions/upload-artifact@v4
      with:
        name: Hedgehog_Sentinel_Windows_Pack
        path: dist/Hedgehog_Sentinel/
